spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/smartvillage
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081

jwt:
  secret: change-me-super-secret
  expiration-ms: 86400000

springdoc:
  api-docs:
    path: /v3/api-docs
